//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace E_shopLib1.Properties {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("E_shopLib1.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на &lt;!DOCTYPE html&gt;
        ///&lt;html lang=&quot;ru&quot;&gt;
        ///&lt;head&gt;
        ///    &lt;meta charset=&quot;UTF-8&quot;&gt;
        ///    &lt;meta name=&quot;viewport&quot; content=&quot;width=device-width, initial-scale=1.0&quot;&gt;
        ///    &lt;title&gt;Чек продажи №{{RECEIPT_NUMBER}}&lt;/title&gt;
        ///    &lt;style&gt;
        ///        * {
        ///            margin: 0;
        ///            padding: 0;
        ///            box-sizing: border-box;
        ///            font-family: &apos;Courier New&apos;, monospace;
        ///        }
        ///        
        ///        body {
        ///            background-color: #f5f5f5;
        ///            padding: 20px;
        ///            display: flex;
        ///            just [остаток строки не уместился]&quot;;.
        /// </summary>
        internal static string SaleCheckTemplate {
            get {
                return ResourceManager.GetString("SaleCheckTemplate", resourceCulture);
                }
        }
        ///    &lt;title&gt;Приходная накладная&lt;/title&gt;
        ///    &lt;style&gt;
        ///        body {
        ///            font-family: &apos;Times New Roman&apos;, serif;
        ///            margin: 0;
        ///            padding: 20px;
        ///            background: white;
        ///            font-size: 14pt;
        ///            line-height: 1.3;
        ///        }
        ///        
        ///        .invoice-container {
        ///            width: 100%;
        ///            max-width: 210mm;
        ///            margin: 0 auto;
        ///            padding: 20px;
        ///           [остаток строки не уместился]&quot;;.
        /// </summary>
        internal static string invoice_template {
            get {
                return ResourceManager.GetString("invoice_template", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Byte[].
        /// </summary>
        internal static byte[] wkhtmltopdf_x64 {
            get {
                object obj = ResourceManager.GetObject("wkhtmltopdf_x64", resourceCulture);
                return ((byte[])(obj));
            }
        }
    }
}
